### ISSUE TITLE
`dvc`: Option to automatically open the html report

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#180]
`dvc plots {show|diff}` have an `--open` option that "opens the generated plot in the browser automatically".

Coming from discussions in https://github.com/iterative/dvc/pull/6815 it looks like having a similar option to automatically open the DVCLive HTML report on the browser would be nice to have.

In addition to whether adding this option is useful (I think it is), questions are where and how would the option be added.

From the top of my head, an additional property to the field in `live` section of `dvc.yaml` would be nice:

```yaml
stages:
   stages:
  train:
    cmd: python train.py
    live:
      dvclive:
        summary: true
        html: true
        open: true
```

As a drawback, this would probably require adding yet another parameter to the long list of `dvc stage add` / `dvc run` options (`--live-open`?).
