### ISSUE TITLE
`dvc`: Enable model loading/saving based on `checkpoint: true`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#191]
Given a DVC stage where `checkpoints` are enabled:

```yaml
stages:
  train:
    cmd: src/train.py
    deps:
    - data
    - src
    outs:
    - model.pth:
        checkpoint: true
    live:
      dvclive:
        summary: true
        html: true
```

Users need to also enable checkpoints on the Python code.

Maybe we could treat the model loading (a lot pending #140)  and model saving similar to how we treat the `path` argument:

A) If `checkpoint: true` is set in DVC and `model_file` is None in DVCLive: we use the value of the output as `model_file` .
B) If `checkpoint: true` is set in DVC and `model_file` is set in DVCLive but does not match: raise `ConfigMismatchError`.
C) If `checkpoint: false`, just use whichever value has `model_file` in DVCLive.
