### ISSUE TITLE
make_dvcyaml: always save dvc.yaml

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#381]
After playing around with `save_dvc_exp` a bit, I think it should always call `make_dvcyaml` even when run with `dvc exp run` or `dvc repro`. It makes the transition to using these smoother since you can keep the existing `dvc.yaml` to configure the metrics and plots.

Edit: I think because my `dvclive/dvc.yaml` file was untracked, it wasn't getting saved once I turned off `save_dvc_exp`. Regardless, I think we should overwrite it on each run to ensure it exists and is up to date.

**Comment by dberenbaum** [comment]
Some notes:

* If there is a `dvclive/dvc.yaml` but no `dvclive/params.yaml`, `dvc.api.params_show()` will complain. Can dvclive add/drop the params section in `dvclive/dvc.yaml` depending on whether `dvclive/params.yaml` exists?
* If I already have a root `dvc.yaml` with stage metrics and plots outputs and generate `dvclive/dvc.yaml`, it will duplicate plots but won't break anything.

If we can make params work, it might make sense to write out `dvclive/dvc.yaml` even when `save_dvc_exp=False`.

**Comment by dberenbaum** [comment]
Another scenario to consider: if I run `dvc exp run` with checkpoints but without metrics/plots configured, it would be useful to call `make_dvcyaml` at each step to get live metrics/plots.

**Comment by dberenbaum** [comment]
I plan to play around with this.

**Comment by dberenbaum** [comment]
@daavoo Added two possibilities in #384 and #385. I'm happy to go with either option for now.

Both always write out `dvc.yaml`. I don't see much downside here. Even if dvc isn't installed, it means I could go back and see metrics, plots, and params if I later install it and add it to my repo.

Both also write out a new `dvc.yaml` at least for each live instance, since it's likely the format will change over time, and this ensures the updates get propagated to the file.

**Comment by dberenbaum** [comment]
Reopening because this behavior was deemed too aggressive in some cases. For now, we can revert this behavior.

Comment from @shcheklein:

> we are generating evaluation:dvc.yaml even when there is a dvc.yaml already in the root. This causes strange effects (rendering of extra plots, some of the one single value (for metrics, since we dump them into plots as well). And at the end - everything is good. I think it’s too noisy / not expected

Let's please keep thinking about how this should behave. I'd still like to be able to generate this when using pipelines so that I don't have to manually configure the plots, metrics, and params myself.

**Comment by dberenbaum** [comment]
In VS Code, hiding these plots can be done in a single click by deselecting the dvclive directory in the plots section in the sidebar, so I don't find it that painful, but maybe there are ways we can better detect whether to either write that dvc.yaml or whether those plots should be shown.

I think it's important to write out dvc.yaml for pipelines because it greatly simplifies the default setup for using dvclive with pipelines. Currently, users need to set up something like this:

```
stages:
  eval:
    cmd: python eval.py
    metrics:
      - dvclive/metrics.json:
    plots:
      - dvclive/plots/metrics
      - dvclive/plots/images
      - dvclive/plots/sklearn/confusion_matrix.json:
          template: confusion
          x: actual
          y: predicted
```

If dvclive writes out its own dvc.yaml, then the pipeline config becomes:

```
stages:
  eval:
    cmd: python eval.py
    outs:
      - dvclive
```
