### ISSUE TITLE
log_plot: allow for `y` to be a list

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#549]
Should we allow for `y` to be a list?

Edit: can be a follow up, so not blocking, but I think it makes it significantly more useful.

_Originally posted by @dberenbaum in https://github.com/iterative/dvclive/pull/543#discussion_r1178251310_

**Comment by jenfredwell** [comment]
+1 for this.  I came here looking for a way to log a plot with a definition like
```
- data.json:
    template: linear
    x: c
    y:
    - a
    - b
```

Is this possible to write directly to data.json instead of `live.log_plot(..)` and have this definition in the `dvc.yaml` file?
