### ISSUE TITLE
System metrics should be plotted with `timestamp` rather than `step`

### ISSUE THREAD

**Issue by AlexandreKempf** [iterative/dvclive#791]
The system metrics should be plotted with `timestamp` rather than `step`. 

TODO list:
- [ ] Live should save in the dvcyaml:
```
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/metrics/system:
    x: timestamp
```
- [ ] Add a new template to display relative timestamp (timestamp axis that start at 0).

Blocker: https://github.com/iterative/dvc/pull/10320
