### ISSUE TITLE
Repeatedly print the same live path to dvc.yaml when specifying multi-level live paths in Windows System

### ISSUE THREAD

**Issue by ws1336** [iterative/dvclive#848]
Platform: Python 3.8.16 on Windows-10-10.0.22631-SP0

dvclive                      3.5.0

Minimum reproducing code，Run this code twice：

```python
from dvclive import Live

with Live(dir="dvclive/subdir") as live:
    live.log_metric("metric", 1)

``` 

The dvc.yaml outputs:
```
metrics:
- dvclive/subdir/metrics.json
- dvclive/subdir/metrics.json
plots:
- dvclive/subdir/plots/metrics:
    x: step
- dvclive/subdir/plots/metrics:
    x: step

``` 

The output I expect：
```
metrics:
- dvclive/subdir/metrics.json
plots:
- dvclive/subdir/plots/metrics:
    x: step

```
